// <auto-generated />
namespace AcademiaDOJO_EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v010 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v010));
        
        string IMigrationMetadata.Id
        {
            get { return "202108121909266_v0.10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
